version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  orderdb:
    container_name: orderdb
    ports:
      - "14333:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd!1"
      ACCEPT_EULA: "Y"
    
  catalog.api:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8000:80"

  basket.api:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=basketdb:6379"
      - "EventBus:HostName=rabbitmq"
      - "EventBus:Username=guest"
      - "EventBus:Password=guest"
    depends_on:
      - basketdb
      - rabbitmq
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8001:80"
  ordering.api:
    container_name: orderingapi
    restart: on-failure 
    depends_on:
      - orderdb
      - rabbitmq
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnection=Server=orderdb,1433;Database=OrderDb;User Id=sa;Password=P@ssw0rd!1"
      - "EventBus:HostName=rabbitmq"
      - "EventBus:Username=guest"
      - "EventBus:Password=guest"
    ports:
      - "8002:80"


  ocelotapigateway:
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "7000:80"

